### ISSUE TITLE
Fatal error in Github Actions

### ISSUE THREAD

**Issue by radaken** [devsecops-learning/docs#17]
![image](https://user-images.githubusercontent.com/50579478/99293147-a88ed500-285b-11eb-9eb2-841c28749813.png)
After adding a `checkRU.yml` in workflow I faced with a problem (pic related), so, I try to google this error but solutions was unacceptable to github, e.g. `Removing the changesets from the database and then re-importing everything seemed to make the error go away.`.

Do not pay attention to zero-commit, thats because I test my guess to internal github error and create other branch `radaken-patch-2`. In `radaken-patch-2` was the same error (but commits are really existed and by logical should be compared)

So, my code using `git diff --name-only` to find changed/added files and compare it with bash command `test -f`

@samoylenko asking for help!!!

**Comment by radaken** [comment]
![image](https://user-images.githubusercontent.com/50579478/99300090-974ac600-2865-11eb-8128-ead62e60006d.png)
now its like

**Comment by radaken** [comment]
When I google this error oftenly I find that people says about force pushing but I never did it in my IDE. Maybe VSCode forcepushing as default? I'll try to working on it using Intellij IDEA

**Comment by radaken** [comment]
Find resolution on [github community website](https://github.community/t/get-changes-from-all-commits-pushed/17639). I should use `${{ github.sha }}` instead `${{ github.event.after` and now it will work. Closes #17

**Comment by samoylenko** [comment]
Let's discuss this tomorrow (Tuesday) in Telegram. Sorry I missed all the notifications while you were doing this.
