### ISSUE TITLE
Русифицировать docs/getting-started

### ISSUE THREAD

**Issue by radaken** [devsecops-learning/docs#2]
Перевести на русский язык.

**Comment by samoylenko** [comment]
Предлагаю добавить второй документ, что-нить типа `getting-started-rus.md`, весь на русском, положить в оба документа ссылки друг на друга. 

Как альтернатива, можно вообще запилить `docs/rus/getting-started.md`  - так многие сайты делают, с отдельной директорией для локализации. То есть у нас сейчас есть общая ссылка https://devsecops-learning.github.io/docs/ (которая пока просто пустая страница), а для русско-язычных, будет "https://devsecops-learning.github.io/docs/rus/getting-started"  (там `rus` в середине
)

**Comment by samoylenko** [comment]
@radaken @sashablacky @Fastex26rus  

Друзья, это хороший пример еще одного важного аспекта: Алексей добавил новую задачу, и мы все можем обсудить. И даже добавить другие задачи в зависимости от обсуждения. Это стандартный подход GitHub для обсуждений. В компаниях - немного не так: там Scrum, и все работают вместе. Там такое обсуждается в так называемых "Grooming" sessions, то есть собираются все новые тикеты, сначала приоретизируются, и потом детально обсуждаются до тех пор, пока не будут признаными готовыми идти в работу (у нас конечно проще и уже можно работать)

**Comment by radaken** [comment]
Я думаю стоит сделать отдельную директорию для русской локализации, т.к.в дальнейшем быть может будут краткие выдержки, шпаргалки или даже полноценная русификация и обзор на нужные нам модули
